filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log

setup.template.name: "business-logs"
setup.template.pattern: "business-logs*"
setup.ilm.enabled: false

output.logstash:
  hosts: ["logstash:5044"]

setup.kibana:
  host: "http://kibana:5601"
